<?php
namespace App\Models;

enum Permission: string{

    // lab related permissions
    case LABORATORY_VIEW_STATS= "LABORATORY.VIEW_STATS";
    CASE LABORATORY_REGISTER_SPECIMEN="LABORATORY.REGISTER_SPECIMEN";
    CASE LABORATORY_ENTER_RESULTS="LABORATORY.ENTER_RESULTS";
    CASE LABORATORY_VIEW_TEST_RESULTS="LABORATORY.VIEW_TEST_RESULTS";
    CASE LABORATORY_VALIDATE_RESULTS="LABORATORY.VALIDATE_RESULTS";
    CASE LABORATORY_MANAGE_BILLING="LABORATORY.MANAGE_BILLING";
    CASE LABORATORY_EXPORT_SHEET="LABORATORY.EXPORT_SHEET";
    case LABORATORY_MANAGE_TEST_TYPE="LABORATORY.MANAGE_TEST_TYPE";
    case LABORATORY_MANAGE_SPECIMEN_TYPE="LABORATORY.MANAGE_SPECIMEN_TYPE";


    // patient related permissions
    case PATIENT_CREATE_PATIENT="PATIENT.CREATE_PATIENT";
    case PATIENT_VIEW_PATIENT_PROFILE="PATIENT.VIEW_PATIENT_PROFILE";
    case PATIENT_VIEW_PATIENTS="PATIENT.VIEW_PATIENTS";
    CASE PATIENT_MODIFY_PATIENT_INFO="PATIENT.MODIFY_PATIENT_INFO";


    // configuration related permissions    
    CASE CONFIGURATION_MANAGE_META="CONFIGURATION.MANAGE_META";
    CASE CONFIGURATION_MANAGE_APP_CONFIG="CONFIGURATION.MANAGE_APP_CONFIG";


    // billing related permissions
    CASE BILLING_CREATE_BILL="BILLING.CREATE_BILL";
    CASE BILLING_VIEW_BILL="BILLING.VIEW_BILL";
    CASE BILLING_MANAGE_SERVICES="BILLING.MANAGE_BILLING_SERVICES";
    CASE BILLING_VIEW_STATS = "BILLING.VIEW_STATS";



     
    CASE  PHARMACY_VIEW_STATS="PHARMACY.VIEW_STATS";
    CASE  PHARMACY_MANAGE_DRUG="PHARMACY.MANAGE_DRUG";
    CASE  PHARMACY_MANAGE_INVENTORY="PHARMACY.MANAGE_INVENTORY";
    CASE  PHARMACY_MANAGE_PRESCRIPTION="PHARMACY.MANAGE_PRESCRIPTIONS";


    //bloodbank related permissions
    CASE  BLOOD_BANK_VIEW_STATS="BLOODBANK.VIEW_STATS";
    CASE  BLOOD_BANK_MANAGE_IO="BLOODBANK.MANAGE_IO";
    CASE  BLOOD_BANK_MANAGE_INVENTORY="BLOODBANK.MANAGE_INVENTORY";
}