<?php
namespace App\Models;

enum Permission: string{
    case VIEW_STATS= "VIEW_STATS";
    case CREATE_PATIENT="CREATE_PATIENT";
    case VIEW_PATIENT_PROFILE="VIEW_PATIENT_PROFILE";
    case MANAGE_TEST_TYPE="MANAGE_TEST_TYPE";
    case MANAGE_SPECIMEN_TYPE="MANAGE_SPECIMEN_TYPE";
    CASE MANAGE_META="MANAGE_META";
    CASE MANAGE_APP_CONFIG="MANAGE_APP_CONFIG";
    CASE REGISTER_SPECIMEN="REGISTER_SPECIMEN";
    CASE ENTER_RESULTS="ENTER_RESULTS";
    CASE VIEW_TEST_RESULTS="VIEW_TEST_RESULTS";
    CASE VALIDATE_RESULTS="VALIDATE_RESULTS";
    CASE MANAGE_BILLING="MANAGE_BILLING";
    CASE EXPORT_SHEET="EXPORT_SHEET";
    CASE MODIFY_PATIENT_INFO="MODIFY_PATIENT_INFO";
}