<template>
    <NuxtLayout name="inner">
        
              <!--start breadcrumb-->
              <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="breadcrumb-title pe-3">Dashboard</div>
                <div class="ps-3">
                  <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0 align-items-center">
                      <li class="breadcrumb-item"><a href="javascript:;">
                          <ion-icon name="home-outline"></ion-icon>
                        </a>
                      </li>
                      <li class="breadcrumb-item active" aria-current="page">Bills</li>
                    </ol>
                  </nav>
                </div>
                
              </div>
              <!--end breadcrumb-->
  
              <div>
              
              
                <!-- <br/>
                <h6 class="mb-0 text-uppercase">Tamko Clarence</h6>
                <hr/> -->
  

                <!-- start -->
                <div class="row">
                
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                              <h4 class="mb-2">Generated Bills</h4>
                              <br/>


                              <div class="table-responsive">

                                <div  class="dataTables_wrapper dt-bootstrap5 dttable_wrapper">
                                     
                               <div class="row">
                                 <div class="col-sm-12">
                                     <table id="onetoabc" class="table table-striped table-bordered dttable " role="grid" aria-describedby="example2_info">
                                       <thead>
                                           <tr role="row">
                                              <th rowspan="1" colspan="1">ID</th>
                                              <th rowspan="1" colspan="1">Date</th>
                                              <th rowspan="1" colspan="1">Patient</th>
                                              <th rowspan="1" colspan="1">Generated By</th>
                                              <th rowspan="1" colspan="1">Test(s)</th>
                                              <th rowspan="1" colspan="1"></th>
                                            </tr>
                                       </thead>
                                       <tbody>
           
                                           
                                       <tr role="row" v-for="(u,i) in bills" :class="i%2==0?'even':'odd'" :key="'account-'+i">
                                               <td class="">BILL_{{u.id}}</td>
                                               <td class="">{{u.created_at}}</td>
                                               <td class="">{{ u.patientname }}</td>
                                               <td class="">{{u.generatedby}}</td>
                                               <td class="">{{u.tests.join(", ")}}</td>
                                               <td>
                                                
                                                <NuxtLink class="btn btn-primary btn-sm" :to="baseUrl+'/bill-report/'+u.id+'.pdf'" target="_blank">View Details</NuxtLink>
                                                <button class="btn btn-danger btn-sm ms-3" @click="deletebill(u)">Delete</button>
                                                
                                                
                                               </td>
                                               
                                         </tr>
                                       </tbody>
                                       <tfoot>
                                            <tr role="row">
                                              <th rowspan="1" colspan="1">ID</th>
                                              <th rowspan="1" colspan="1">Date</th>
                                              <th rowspan="1" colspan="1">Patient</th>
                                              <th rowspan="1" colspan="1">Generated By</th>
                                              <th rowspan="1" colspan="1">Test(s)</th>
                                              <th rowspan="1" colspan="1"></th>
                                            </tr>
                                       </tfoot>
                                   </table>
                                 </div>
                               </div>
                   
                                 </div>
                             </div>
                              
                            
    
    
    
                           
                            <!-- tab ends here -->
                            </div>
                          </div>
                    </div>
                  </div>
                  <!-- end -->
  
  
                </div>
  
      
    
  
    </NuxtLayout>
  </template>

  <script>
  export default{
    methods:{
      loadData(){
            const context=this;
            getRequestLoad_('/bills/',{},(bills)=>{
              context.bills= bills;
              setTimeout(() => {
                loadDataTables();
              }, 500);
            });
      },
      deletebill(data){
        const context=this;
        if(window.confirm("Are you sure you want to delete this bill?")){
          getRequestLoad_("/bill/"+data.id+"/delete",{},()=>{
                context.loadData();
          });
        }
      }
    },
    data(){
        return {
          bills:[],
          baseUrl:BASE_URL
        };
    },
    mounted(){
      this.loadData();
    }
  }
  </script>